---
# tasks file for debugging
# Example that prints the loopback address and gateway for each host
- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Test group vars
  debug:
    msg: "Value of vars : {{ item }}"
